image: node:lts

before_script:
  - yarn install

pages:

  script:
    - yarn run build
    - mkdir public
    - mv demo/* public
    - mv dist/* public
    - mv assets/* public

  artifacts:
    paths:
      - public

  only:
    - master
